# Generated by Django 3.2.2 on 2021-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=100)),
                ('note_text', models.CharField(max_length=500)),
                ('pud_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
