# Generated by Django 3.2.2 on 2021-06-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_related_note_comments_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='text',
            new_name='quick_note',
        ),
    ]
