# Generated by Django 3.2.2 on 2021-06-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_text_notes_quick_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='notes',
            new_name='Note',
        ),
    ]
