# Generated by Django 3.2.2 on 2021-06-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_time',
        ),
    ]
