# Generated by Django 3.2.2 on 2021-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
