# Generated by Django 3.2.2 on 2021-05-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
