# Generated by Django 3.2.2 on 2021-06-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note_title',
            new_name='title',
        ),
    ]
