# Generated by Django 3.2.2 on 2021-06-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210601_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='note',
            new_name='note_id',
        ),
    ]
