# Generated by Django 3.2.2 on 2021-06-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_note_comments_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='note_id',
            new_name='related_note',
        ),
    ]
