# Generated by Django 3.2.2 on 2021-06-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_note_id_comments_related_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='related_note',
            new_name='note',
        ),
    ]
